name: EcoCity 360 - CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    name: Build e Testes Automatizados
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v3

      - name: Configurar o .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --no-restore --configuration Release

      - name: Rodar Testes Unitarios
        run: dotnet test --no-build --configuration Release --verbosity normal

  deploy-staging:
    name: Deploy Staging
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://github.com

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v3

      - name: Build da Imagem Docker
        run: docker build -t ecocity-api:staging -f EcoCity/Dockerfile ./EcoCity

      - name: Simular entrega no servidor
        run: echo "Imagem gerada e implantada no ambiente de Staging com sucesso!"

  deploy-producao:
    name: Deploy Producao
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: Producao
      url: https://github.com

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v3

      - name: Build da Imagem Docker
        run: docker build -t ecocity-api:latest -f EcoCity/Dockerfile ./EcoCity

      - name: Simular entrega no servidor
        run: echo "Imagem de Producao gerada e implantada com sucesso!"